name: new pull request

on:
  pull_request:
    branches:
      - main
    types: [opened]

permissions:
  contents: read

jobs:
  new-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: fence
        uses: openai/fence@6ddc6df2e7dd8826022809a8143573247fb3b486 # pin@v0.10.3
        with:
          mode: audit

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          persist-credentials: false

      - name: comment with deployment instructions
        uses: GrantBirki/comment@937820f3623fd0e300294bcc64ac7577fc0ad4cc # pin@v3.0.3
        continue-on-error: true
        with:
          body: |
            ### 👋 Thanks for opening a pull request!

            If you are new, please read the deployment instructions below to learn how to ship your changes to production:

            1. 🧪 Run a noop deployment with `.noop` as a comment on this PR
            1. 👀 Observe the CI and `noop` output on this pull request to ensure it is passing and doing what it is supposed to do
            1. ✔️ Obtain an approval/review on this pull request
            1. 🚀 Branch deploy your pull request to production with `.deploy`

                &gt; If anything goes wrong, rollback with `.deploy main`

            1. 🎉 Merge!

            If you need additional help, please view the [usage guide](https://github.com/grantbirki/branch-deploy/blob/main/docs/usage.md).
